#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config click_to_focus      true

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

bspc config ignore_ewmh_focus   true # Do not follow opened windows when requested

# xrdb
function get_xrdb() {
  xrdb -query | grep "$1" | awk '{print $2}' | tail -n1
}

bspc config normal_border_color "$(get_xrdb background)"

bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled
bspc rule -a firefox border=off
bspc rule -a feh state=floating border=off
bspc rule -a tabbed state=floating border=off
bspc rule -a Emacs state=tiled

# Set wallpaper
feh --bg-fill ~/.config/wall

# Autostart
killall -9 polybar redshift dunst

$HOME/.config/polybar/launch.sh
redshift -l 49.1:-123.7 -t 5700:3000 &
flameshot &
dunst &

# Default workspace
bspc rule -a firefox -o desktop=I && firefox -new-tab moz-extension://6a6f793c-08ee-49af-bc64-b4a0b352a519/index.html & # Start with new tab

bspc rule -a Tilix:tilix -o desktop=IX && tilix -e spt &

sleep 20

bspc rule -a Emacs -o desktop=X && emacsclient -nc --eval "(org-agenda-list)" &
bspc rule -a Gnome-calendar -o desktop=X && gnome-calendar &
bspc rule -a Geary -o desktop=X && geary &
