#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        16
bspc config window_gap          16

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config click_to_focus      true

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

# xrdb
function get_xrdb() {
  xrdb -query | grep "$1" | awk '{print $2}' | tail -n1
}
xrdb -merge "${HOME}/.Xresources"

bspc config normal_border_color "$(get_xrdb background)"
bspc config focused_border_color "$(get_xrdb background)"

bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Firefox border=off
bspc rule -a feh state=floating border=off
bspc rule -a albert border=off
bspc rule -a Emacs state=tiled
bspc rule -a URxvt:urxvt_keys_help state=floating

# Set wallpaper
feh --bg-fill ~/Drive/Resources/Wallpapers/earth.png

# Set custom keyboard configuration
#setxkbmap -option caps:escape
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape'
setxkbmap -option "shift:both_capslock"
setxkbmap -option compose:ralt

killall -9 sxhkd polybar redshift compton insync dunst syncthing

sxhkd &

polybar -r main &

#Redshift
redshift -l 49.1:-123.7 -t 5700:3000 &

compton --config ~/.config/compton.conf -b &

insync start --headless &

dunst &

syncthing &
