#!/bin/sh

compositor=river

export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=$compositor
export XDG_CURRENT_DESKTOP=$compositor

export MOZ_ENABLE_WAYLAND=1
export CLUTTER_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export ECORE_EVAS_ENGINE=wayland-egl
export ELM_ENGINE=wayland_egl
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export NO_AT_BRIDGE=1

# xdg-desktop-portal-wlr
# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
