#! /bin/zsh

# See xrandr --listmonitors
if [ $(cat /etc/hostname) = egret ]; then
    bspc monitor DisplayPort-0 -d I II III IV V VI VII
    bspc monitor HDMI-A-0 -d VIII IX X
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

# TODO: Duplicate with .zshrc
# This function must be defined before .zshrc because bspwmrc is called by
# .xinitrc
function get_xrdb() {
  xrdb -query | grep "$1" | awk '{print $2}' | tail -n1
}

bspc config border_width        4
bspc config window_gap          8

bspc config split_ratio         0.5
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config click_to_focus      true
# bspc config focus_follows_pointer true

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0

 # Do not follow opened windows when requested
bspc config ignore_ewmh_focus   true

# Smooth movement of floating windows
# bspc config pointer_motion_interval 1

bspc config normal_border_color "$(get_xrdb background)"
bspc config focused_border_color "$(get_xrdb color3)"

bspc rule -a Pavucontrol state=floating
bspc rule -a Zathura state=tiled
bspc rule -a feh state=floating border=off
bspc rule -a Emacs state=tiled

# Set wallpaper randomly
# feh --bg-fill $(find ~/Pictures/Wallpapers/**/*.jpg | shuf -n 1) $
$HOME/scripts/wallpaper-unsplash &

# Set cursor to pointer instead of cross
xsetroot -cursor_name left_ptr

# Autostart
killall sxhkd polybar redshift dunst copyq picom nextcloud

sxhkd &
$HOME/.config/polybar/launch.sh
redshift-gtk -l 49.1:-123.7 -t 6000:2700 &
flameshot &
dunst &
# nm-applet &
greenclip daemon &
picom --experimental-backends &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Vim LaTeX
inkscape-figures watch &
python ~/.local/bin/inkscape-shortcut-manager/main.py &

killall tilix geary emacs minetime
# Default workspace
# bspc rule -a Emacs -o desktop=I && emacsclient -nc &
# Emacs needs a few seconds to start
# sleep 5

bspc rule -a Chromium -o desktop=VII && spotify-launcher
bspc rule -a kalendar -o desktop=X && kalendar &
bspc rule -a Ferdium -o desktop=X && ferdium &
bspc node @X:/ -R 180

bspc desktop -f ^10
bspc desktop -f ^1
